my_data_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: maria
      password: maria123
      port: 5432
      dbname: lab_database
      schema: dbt
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10